<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
 [
                'id' => 22,
                'name' => 'Táo Breeze (1kg)',
                'price' => 80000,
                'description' => 'Táo Breeze NewZealand và Mỹ là một loại táo nhỏ có khối lượng từ 180-220gr/quảnh năm của Mỹ và NZ.\n\n\nTáo Breeze NZ giòn hơn táo Breeze Mỹ. Táo có vị ngọt vừa và giòn tùy vào mùa',
                'category_id' => 1,
                'thumbnail' => '17017007572901459.jpg',
                'quantity' => 55,
            ],
            [
                'id' => 23,
                'name' => 'Táo Koru Mỹ (1kg)',
                'price' => 110000,
                'description' => 'Táo Koru Mỹ có hình tròn, màu đỏ sẫm, vỏ mỏng thịt cứng và ngọt. Táo koru ên, sức tiêu thụ của loại táo này tại thị trường Việt Nam còn thấp.táo koru có giòn khôngTáo koru Mỹ',
                'category_id' => 1,
                'thumbnail' => '1701700816tao-koru-my.jpg',
                'quantity' => 32,
            ],
            [
                'id' => 24,
                'name' => 'Táo Queen (1kg)',
                'price' => 55000,
                'description' => 'Táo Queen là một loại táo được sử dụng nhiều ở vùng châu Âu. Ở thị trư có hình tròn hoặc hình chuông. Cứng giòn và ngọt.Táo Queen NZ ngon hơn táo Queen của Mỹ. Mỗi quả nặng từ',
                'category_id' => 1,
                'thumbnail' => '17017009272901460.jpg',
                'quantity' => 67,
            ],
            [
                'id' => 25,
                'name' => 'Táo xanh Mỹ/Pháp (1kg)',
                'price' => 130000,
                'description' => 'Táo xanh Mỹ như dòng Smith, dòng gấu có mùi thơm, quả bóng loáng và cựính chua của nó mang lại. Táo sẽ ăn ngon khi chấm muối tôm.   Độ giòn: 7.5 điểm Độ ngọt: 0 điểm Mức giá: 95-105',
                'category_id' => 1,
                'thumbnail' => '1701700971apple1.jpg',
                'quantity' => 44,
            ],
            [
                'id' => 26,
                'name' => 'Táo Fuji Mỹ (1kg)',
                'price' => 90000,
                'description' => 'Táo Fuji Mỹ là một loại táo tầm trung được nhiều người Việt ưa chuộnTáo có tính ổn định cao, ngọt vừa và giòn vừa phải. Mức giá khá phù hợp để sử dụng.Độ giòn: 7 điểmĐộ ngọt',
                'category_id' => 1,
                'thumbnail' => '1701701378táo fuji.jpg',
                'quantity' => 11,
            ],
            [
                'id' => 27,
                'name' => 'Táo Juliet Pháp (1kg)',
                'price' => 75000,
                'description' => 'Táo juliet Pháp là giống táo được trồng theo chuẩn hữu cơ. Táo có đ suốt mùa vụ. Hiện tại thời vụ của táo này rơi vào tháng 1 đến tháng 4. Táo chưa phổ biến tại thị trường Việtl',
                'category_id' => 1,
                'thumbnail' => '1701701449juliet phap.jpg',
                'quantity' => 30,
            ],
            [
                'id' => 28,
                'name' => 'Táo Fuji Nhật  (1kg)',
                'price' => 65000,
                'description' => 'Siêu phẩm táo đỏ Fuji Nhật cực thơm, khá giòn và ngọt. Vì thế giá i táo này tại Việt Nam còn kén.Táo này phù hợp làm quà biếu sang chảnh. Mùa vụ rơi vào mùa hè từ tháng 4 đến th',
                'category_id' => 1,
                'thumbnail' => '1701701813fuji nhật.jpg',
                'quantity' => 22,
            ],
            [
                'id' => 29,
                'name' => 'Chuối tây (5 quả)',
                'price' => 30000,
                'description' => 'Chuối tây là loại chuối lùn, giống chuối này rất dễ phân biệt bởi q Đa số, chuối khi chín có vỏ dày và màu vàng nhạt, ruột màu trắng. Bạn sẽ ăn được nhiều và lâu chán vì thịt chuối',
                'category_id' => 1,
                'thumbnail' => '17017035852901100.jpg',
                'quantity' => 21,
            ],
            [
                'id' => 30,
                'name' => 'Chuối cau (5 quả)',
                'price' => 20000,
                'description' => 'Sở dĩ được gọi là chuối cau bởi giống chuối này có quả nhỏ, hướng trng bị nhầm lẫn.\n\nTuy nhiên, quan sát kĩ hơn ta thấy chuối cau có mật độ quả nhiều hơn, lớp vỏ mịn, quả tròn hơn',
                'category_id' => 1,
                'thumbnail' => '17017036432901099.jpg',
                'quantity' => 44,
            ],
            [
                'id' => 31,
                'name' => 'Chuối ngự (5 quả)',
                'price' => 35000,
                'description' => 'Cũng giống như chuối cau, chuối ngự là loại quả rất quen thuộc, có hìnà chuối cau dễ dàng.\r\n\r\nChuối ngự khi chín quả c',
                'category_id' => 1,
                'thumbnail' => '17017036892901141.jpg',
                'quantity' => 44,
            ],
            [
                'id' => 32,
                'name' => 'Chuối tiêu (5 quả)',
                'price' => 0,
                'description' => 'Chuối tiêu chắc hẳn không xa lạ gì đối với những tín đồ của chuối. Chuối tiêu thường có hai loại là chuối tiêu lùn và chuối ti chưa chín vỏ có màu xanh đậm và khi chín vỏ chuyển sang màu và',
                'category_id' => 1,
                'thumbnail' => '1701703787tiêu.jpg',
                'quantity' => 32,
            ],
            [
                'id' => 33,
                'name' => 'Nho Sweet Globe Mỹ',
                'price' => 100000,
                'description' => 'Đứng đầu trong danh sách trái cây nhập khẩu hàng đầu của ngày hôm nay là sản phẩm nho xanh Sweet Globe Mỹ, đây là loại nho nhập khẩu rấtà không có hạt rất phù hợp với con trẻ của bạn.\n\nBên cạn',
                'category_id' => 1,
                'thumbnail' => '1701703921graps_white.jpg',
                'quantity' => 55,
            ],
            [
                'id' => 34,
                'name' => 'Nho đỏ Mỹ',
                'price' => 160000,
                'description' => 'Bên cạnh hương vị thơm ngon nổi bật của mình, các loại nho đỏ có nguồn gốc xuất sứ đến từ Mỹ còn rất được đông đảo gia đình lựa chmáu não cũng như ngăn ngừa các triệu chứng ung thư',
                'category_id' => 1,
                'thumbnail' => '17017039692901051_19.jpg',
                'quantity' => 0,
            ],
            [
                'id' => 35,
                'name' => 'Nho tím Anthony',
                'price' => 200000,
                'description' => 'Nếu như bạn đã cảm thấy chán nản với hương vị của các loại nho thông thường thì hãy hướng đến trải nghiệm cho mình cình hương vị thơm ngon ngọt ngào như kẹo bông tưởng chừng như chỉ c',
                'category_id' => 1,
                'thumbnail' => '1701704079tím kẹo.jpg',
                'quantity' => 34,
            ],
            [
                'id' => 36,
                'name' => 'Cải thìa',
                'price' => 15000,
                'description' => 'Hai vị chuyên gia này đánh giá: Các loại rau họ cải có thể làm giảm nguy cơ bị K và chứa các chất dinh dưỡng chống lại chất gây tế blate và selen. Những chất này đã được chứng minh là có thể làm chậm sự p',
                'category_id' => 2,
                'thumbnail' => '1701704233Cải thìa.jpg',
                'quantity' => 25,
            ],
            [
                'id' => 37,
                'name' => 'Cải xoong',
                'price' => 10000,
                'description' => 'Trung tâm Kiểm soát và Phòng ngừa dịch bệnh (CDC) Mỹ đã xếp cải xoong vào danh sách giàu dưỡng chất. Loại rau này có nhihợp để ăn mỗi ngày.Bên cạnh đó, cải xoong còn chứa nhiều chất xơ gi',
                'category_id' => 2,
                'thumbnail' => '1701704550Thiết kế chưa có tên.jpg',
                'quantity' => 40,
            ],
            [
                'id' => 38,
                'name' => 'Rau muống',
                'price' => 14000,
                'description' => 'Các chuyên gia dinh dưỡng nói rằng: Rau muống là loại rau có hàm lượng cellulose, lignin và pectin dồi dào. Trong đó, chất độc hại trong cơ thể. Nhờ vậy mà giúp thanh lọc cơ thể. Lignin thì có khả năng',
                'category_id' => 2,
                'thumbnail' => '1701704412Rau muống.jpg',
                'quantity' => 33,
            ],
            [
                'id' => 39,
                'name' => 'Rau bina',
                'price' => 18000,
                'description' => 'Đánh giá về rau bina, hai vị chuyên gia cho rằng: Loại rau này chứa đầy carotenoid giúp quét sạch các gốc tự dora tổn thương tế bào, tăng nguy cơ hình thành khối u. Nhiều nghiên cứu cũng chứng mi',
                'category_id' => 2,
                'thumbnail' => '1701704659Rau bina.jpg',
                'quantity' => 33,
            ],
            [
                'id' => 40,
                'name' => 'Nấm hải sản',
                'price' => 12000,
                'description' => 'Nấm là thực phẩm có sự đa dạng về chủng loại cũng như cách chế biến. Loại thực phẩm này cũng rất ngonại thực phẩm thân thiện, có ích cho sức khỏe. \n\nCụ thể, trong nấm có chứa  β-D-Glucosida',
                'category_id' => 2,
                'thumbnail' => '1701704766Nấm.jpg',
                'quantity' => 42,
            ],
            [
                'id' => 41,
                'name' => 'hạt điều',
                'price' => 162000,
                'description' => 'Hạt điều Terrasoul nhập khẩu trực tiếp từ Mỹ. Hạt được tách vỏ sấy khô và đóng hộp. Hạt có giá trị sử rong các dịp lễ. Đặc biệt phù hợp dân văn phòng. Sản phẩm thích hợp dùng trong ngày tết 2019\r\n\r\n',
                'category_id' => 3,
                'thumbnail' => '1701705431điều.jpg',
                'quantity' => 13,
            ],
            [
                'id' => 42,
                'name' => 'hạnh nhân',
                'price' => 199000,
                'description' => 'Hạt hạnh nhân Mourad’s 500gr bóc sẵn vỏ Úc. Sản phẩm nhập khẩu chính ngạch. Phù hợp cho làm bánh, ăn vặt hoặc dùng để làm được nhiều người tin dùng.\n\nQuy cách: 500gr\nXuất xứ: Úc',
                'category_id' => 3,
                'thumbnail' => '1701705477hạnh nhân.jpg',
                'quantity' => 22,
            ],
            [
                'id' => 43,
                'name' => 'hạt macca',
                'price' => 149000,
                'description' => 'Hạt Macca  chứa nhiều chất dinh dưỡng, ít đường, chứa dầu thực vật. Hạt được sấy khô, bảo quản trong bì kín hút chân không.\r\n\r\nQuy cách: 500gr/bịch\r\nXuất xứ: Lâm Đồng',
                'category_id' => 3,
                'thumbnail' => '1701705519macca.jpg',
                'quantity' => 34,
            ],
            [
                'id' => 44,
                'name' => 'nho khô',
                'price' => 88000,
                'description' => 'Nho khô nguyên cành Crimson nhập khẩu trực tiếp từ Úc. Nho được sấy nguyên cành, có vị ngọt mật và thơm. Thích hợp ợp dùng trong ngày tết 2019\r\n\r\nQuy cách: 0.2kg\r\nXuất xứ: Úc',
                'category_id' => 3,
                'thumbnail' => '1701705569nho khô.jpg',
                'quantity' => 9,
            ],
            [
                'id' => 45,
                'name' => 'hạt dẻ cười',
                'price' => 189000,
                'description' => 'Hạt Dẻ Cười Mourad’s Úc 500g ( Không Tẩy Trắng) hay còn goi là Hồ Trăn. Ngăn ngừa bệnh tim mạch, đột quỵ, tiểmáu. Sản phẩm thích hợp dùng trong ngày tết 2019\r\n\r\nQuy cách: 500g/g',
                'category_id' => 3,
                'thumbnail' => '1701705628dẻ cười.jpg',
                'quantity' => 40,
            ],
            [
                'id' => 46,
                'name' => 'rau cần tây',
                'price' => 20000,
                'description' => 'Cây cần tây vừa là một loại rau vừa là vị thuốc quý. Do chứa tới 95% nước nên nhiều người vẫn cho rằng loạiế là, rau cần tây chứa rất nhiều vitamin và khoáng chất quan trọng cho sức khỏe:\r\n\r\nThành phầ',
                'category_id' => 3,
                'thumbnail' => '1701706321cần tây.jpg',
                'quantity' => 37,
            ],

        ]);
}
}
